version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: myecommerce-postgres
    environment:
      POSTGRES_PASSWORD: admin123
      POSTGRES_USER: postgres
      POSTGRES_DB: myecommerce
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: myecommerce-redis
    command: redis-server --requirepass redis123
    ports:
      - "6379:6379"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: myecommerce-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: rabbit123
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped

volumes:
  pg_data: 